// <auto-generated />
using Microsoft.EntityFrameworkCore;
using Microsoft.EntityFrameworkCore.Infrastructure;
using Microsoft.EntityFrameworkCore.Migrations;
using Microsoft.EntityFrameworkCore.Storage.ValueConversion;
using UniSky.Notifications.Data;

#nullable disable

namespace UniSky.Notifications.Migrations
{
    [DbContext(typeof(NotificationDbContext))]
    [Migration("20251214163649_InitialMigration")]
    partial class InitialMigration
    {
        /// <inheritdoc />
        protected override void BuildTargetModel(ModelBuilder modelBuilder)
        {
#pragma warning disable 612, 618
            modelBuilder.HasAnnotation("ProductVersion", "9.0.10");

            modelBuilder.Entity("UniSky.Notifications.Data.NotificationRegistration", b =>
                {
                    b.Property<string>("Did")
                        .HasColumnType("TEXT");

                    b.Property<string>("InstallId")
                        .HasColumnType("TEXT");

                    b.Property<string>("ChannelUrl")
                        .IsRequired()
                        .HasColumnType("TEXT");

                    b.Property<int>("Options")
                        .HasColumnType("INTEGER");

                    b.HasKey("Did", "InstallId");

                    b.HasIndex("ChannelUrl")
                        .IsUnique();

                    b.HasIndex("Did");

                    b.ToTable("Registrations");
                });
#pragma warning restore 612, 618
        }
    }
}
